---
version: "3.9"
services:
  api:
    build: .
    image: kopernick/histmap-api:latest
    environment:
      - NODE_OPTIONS=--max_old_space_size=32768
    command: 'npx lerna run --scope api --stream start:prod'
    expose:
      - 3000

  front-proxy:
    build:
      dockerfile: ./docker/Dockerfile.proxy
      context: .
    image: kopernick/histmap-front-proxy:latest
    ports:
      - 80:80
    depends_on:
      - api
